server:
  port: 8081

spring:
  application:
     name: auth-service
  datasource:
    url: jdbc:postgresql://localhost:5432/auth_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true
    
    properties:
      hibernate:
        format_sql: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
      

jwt:
  secret: 4e7f8c9d2a1b6e5f7d8c9a0b1c2d3e4f5a6b7c8d9e0f123456789abcdef1234
  expiration: 3600000